### PR TITLE
Upgrade jszip to the current version, introduce support for Promises

### PR DESCRIPTION
**Pull request by prantlf**

### CODE REVIEW

**Comment by jsantell** [comment]
Thanks for these PRs! Looking forward to checking them out

**Comment by Georgegriff** [comment]
@jsantell @prantlf Hey we're hitting this issue with the code blocking our server API calls. It would be great to get this PR moving, is there anything I can do to help move this along?

**Comment by jsantell** [comment]
This patch required upgrading a few other components, issues with `unzip`, and a regression in saving empty directories in output. I'll merge this in and add a patch to fix the dependencies and release on top of that https://github.com/EvanOxfeld/node-unzip/issues/134

**Comment by jsantell** [comment]
Published as [2.0.0](https://www.npmjs.com/package/zip-dir)

**Comment by Georgegriff** [comment]
Awesome 🥇

**Pull request merged**
